### ISSUE TITLE
Mac start.sh returns error "docker does not seem to be running" even if docker for Mac is running.

### ISSUE THREAD

**Issue by brianmwhite** [flytbase/flytsim-docker#2]
This [line](https://github.com/flytbase/flytsim-docker/blob/ab99eb3f7ed6abda050e499a4732ef9726a9c974/mac/start.sh#L20) in start.sh fails to find the running docker process on a Mac.

```bash
if ! pgrep com.docker.slirp > /dev/null; then echo -e "${RED}ERROR${NC}: docker does not seem to be running, has it been installed correctly? ${YLW}Try rebooting your machine or start docker from GUI${NC} before running this script${NC}";exit 1;fi
```

I have Docker for Mac installed, version 17.12.0-ce-mac49
If I change com.docker.slirp to com.docker.supervisor it does successfully detect that docker is running but I don't know if that is the right solution. I'm not sure if the other references to slirp in the script are still valid.

This gist seems to be in the right direction. Worked on my Mac for detecting docker installed and docker running:

https://gist.github.com/ekristen/11254304

```bash
if [ "x$(which docker)" == "x" ]; then
  echo "UNKNOWN - Missing docker binary"
  exit 3
fi

docker info > /dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "UNKNOWN - Unable to talk to the docker daemon"
  exit 3
fi
```

**Comment by sharvashish** [comment]
Hi @brianmwhite ,
Thank You for pointing out the bug.
It seems the process name got changed in later releases of Docker.

Thank you for sharing a seemingly better approach to check docker instance. I would definitely add this to our backlog.

Thanks again.

**Comment by imutkarshpatil** [comment]
Changing from this
```
if ! pgrep com.docker.slirp > /dev/null; then echo -e "${RED}ERROR${NC}: docker does not seem to be running, has it been installed correctly? ${YLW}Try rebooting your machine or start docker from GUI${NC} before running this script${NC}";exit 1;fi
```
to this
```
if [ ! pgrep com.docker.slirp > /dev/null ]; then echo -e "${RED}ERROR${NC}: docker does not seem to be running, has it been installed correctly? ${YLW}Try rebooting your machine or start docker from GUI${NC} before running this script${NC}";exit 1;fi
```
worked for me.

Is it required to verify `com.docker.supervisor` ?

**Comment by sharvashish** [comment]
@imutkarshpatil , 
Thanks for the help. We will test it and update the script accordingly.

>  it required to verify com.docker.supervisor ?

There are some basic sanity checks in the code. In general, checking whether 'Docker for Mac' is running or not, is more than enough.
In case, you find some other important checks that must be done, please post them as a separate issue and we will try to accommodate them in our development plan.
